env: prod

database:
  iam:
    read:
      dsn: "postgres://oauth2:oauth2pass@db-replica:5432/oauth2db?sslmode=disable"
    write:
      dsn: "postgres://oauth2:oauth2pass@db-primary:5432/oauth2db?sslmode=disable"
migrate:
  on_start: true
  driver: "postgres"
  dsn: "postgres://oauth2:oauth2pass@localhost:5432/oauth2db?sslmode=disable"
  cmd: "up"
  target: 0

seed:
  on_start: false
  driver: "postgres"
  dsn: "postgres://oauth2:oauth2pass@localhost:5432/oauth2db?sslmode=disable"
  cmd: "up"
  target: 0
